### PR TITLE
feat: add simple GitHub actions

### PR DESCRIPTION
**Pull request by wischli**
* Adds rust toolchain (matching [the one from Polkadot v0.9.43](https://github.com/centrifuge/centrifuge-chain/blob/polkadot-v0.9.43/rust-toolchain.toml))
* Adds simple sanity checks Github actions
  * Pulls used rust toolchain from repository

### CODE REVIEW

**Review by lemunozm — APPROVED** [review]
Awesome @wischli!

Thanks for adding this needed PR 🙌🏻

**Comment by lemunozm** [comment]
I'm not sure if it should have been run for this PR 🤔

**Comment by wischli** [comment]
It should as the proposed github action triggers for any PR against `main`.

**Comment by lemunozm** [comment]
Yeah sorry, it worked! 

I've seen it took only 5 minutes and automatically I thought it didn't haha. It is quite fast not having the runtimes

**Comment by wischli** [comment]
> Yeah sorry, it worked!
> 
> I've seen it took only 5 minutes and automatically I thought it didn't haha. It is quite fast not having the runtimes

Yeah I was amazed as well 🤩

**Pull request merged**
